export const ONE_MINUTE_SECONDS = 60;
export const ONE_HOUR_SECONDS = ONE_MINUTE_SECONDS * 60;
export const ONE_DAY_SECONDS = ONE_HOUR_SECONDS * 24;
export const ONE_WEEK_SECONDS = ONE_DAY_SECONDS * 24;
export const ONE_WEEK_MILLIS = 7 * 24 * 60 * 60 * 1000;