name: Angular Chat Application CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  package-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t teri1712/chat-app-client .

      - name: Push image
        run: docker push teri1712/chat-app-client
